services:
  app:
    build: .
    depends_on:
      - db
    env_file: .env.docker
    command: bundle exec rails s -b '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - .:/ruby-vagas

  db:
    image: postgres:16
    env_file: .env.docker
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data:
